### ISSUE TITLE
Run compute-sanitizer memcheck on tests

### ISSUE THREAD

**Issue by jlowe** [NVIDIA/spark-rapids-jni#1221]
We should leverage compute-sanitizer in memcheck mode in our unit tests to help catch any kernels that may be doing something incorrectly.  Ideally the compute-sanitizer would run with no memory pooling, as memory allocation pooling can hide some invalid memory access patterns from the compute sanitizer.

**Comment by firestarman** [comment]
Seems unit tests expecting errors/exceptions are not suitable to run with the sanitizer, e.g. `CudaFatalTest`. Because saniziter will report errors for this kind of tests but the errors are expected.

We are likely to split these tests away and enable sanitizer only for the tests not test exceptions.

@jlowe What's your idea on this?

**Comment by firestarman** [comment]
@jlowe 
Currently we have two options for testing, with `CuFileTest` and without `CuFileTest` (a profile). If adding the sanitizer support by new maven profiles, we will be likely to have 4 options in total (two new options by maven profiles: sanitizer+CuFileTest, sanitizer+"no CuFileTest"), which seems a little complicated.

Shall we always enable the sanitizer for both of the current two cases, instead of using the maven profile for simplicity ?

**Comment by jlowe** [comment]
I'm not sure it's really that complicated, especially if we work through how to properly inherit between the profiles such that one profile simply sets up the `jvm` tag in surefire to run the sanitizer and the other profile simply sets the tests to run.  Then you can independently enable surefire from which tests to run by simply specifying the corresponding profiles.

If we can't figure out how to merge the surefire settings between the profiles then I'm fine with hardcoding the sanitizer for now.

**Comment by firestarman** [comment]
>especially if we work through how to properly inherit between the profiles such that one profile simply sets up the jvm tag in surefire to run the sanitizer and the other profile simply sets the tests to run. 

Good suggestion, I figoured out a way to do this. 
Could your help review https://github.com/NVIDIA/spark-rapids-jni/pull/1321 again ? 
And it now depends on a cudf PR https://github.com/rapidsai/cudf/pull/13872.

**Comment by firestarman** [comment]
Please note it will take much more time to run the tests with the compute sanitizer. There are some numbers for some tests that the elapsed time became quite long.

|Test|No Sanitizer|With Sanitizer|
|--|--|--|
| Aggregation128UtilsTest| 2.54 s| 8.281 s |
| BinaryOpTest | 0.168 s  | 3.36 s |
| ColumnVectorTest  | 0.912 s | 21.192 s |
| ReductionTest |0.104 s | 4.757 s|
|TableTest| 2.385 s  | 124.59 s|
| ColumnViewNonEmptyNullsTest | 2.615 s | 8.385 s |

**Comment by firestarman** [comment]
3 follow-ups
https://github.com/NVIDIA/spark-rapids-jni/issues/1336
https://github.com/NVIDIA/spark-rapids-jni/issues/1337
https://github.com/NVIDIA/spark-rapids-jni/issues/1338
