### ISSUE TITLE
[BUG] getJsonObject gets infinity instead of zero for a very small float number

### ISSUE THREAD

**Issue by res-life** [NVIDIA/spark-rapids-jni#1923]
**Describe the bug**
CPU gets zero for number: 9.299999257686047e-0005603333574677677
But GPU gets infinity.
The number is a very small value nearly zero, so zero is the correct answer.

**Steps/Code to reproduce bug**
get_json_object("9.299999257686047e-0005603333574677677", "$")
CPU: 0.0
GPU: infinity

**Additional context**
JNI uses cuDF `string to double` and `double to string`.
cuDF can not hanlde very small float value, need to discuss how to fix:
- fix in JNI
- fix in cuDF

**Comment by thirtiseven** [comment]
For number normalization, first use `stod` to convert string to double, then convert back to string with `ftos_converter`:
```
double d_value = cudf::strings::detail::stod(cudf::string_view(current_token_start_pos, number_token_len))
return spark_rapids_jni::ftos_converter::double_normalization(d_value, destination)
```

It seems that `cudf::strings::detail::stod` will return inf for this case, because the precision is very large for a normal use of string to double. We could try to have a workaround in jni to fix this issue.

I tested that in jni's string to double kernel, this case will return null. maybe investigating on how jackson handles this issue can be helpful.

**Comment by res-life** [comment]
Haoyang filed one follow-up issue in cuDF repo:  https://github.com/rapidsai/cudf/issues/15508

**Comment by thirtiseven** [comment]
Filed https://github.com/rapidsai/cudf/issues/15508 in cuDF. 

I use cuDF’s implementation because our string to double does not have a single kernel to call easily, It needs some refactoring to be used for getJsonObject or other usage. And it is not a bit to bit match to Spark also, although it should be much closer than one in cuDF, we might want to fix it in a long term.

**Comment by revans2** [comment]
> we might want to fix it in a long term.

Then please file an issue to do so.

**Comment by res-life** [comment]
> > we might want to fix it in a long term.
> 
> Then please file an issue to do so.

Filed [an issue](https://github.com/NVIDIA/spark-rapids-jni/issues/1963) to track

**Comment by res-life** [comment]
Close this issue as PR #1944 merged.
