### ISSUE TITLE
[BUG] Failed to register cuFile handle: internal error running CuFileTest

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids-jni#238]
**Describe the bug**
Running CuFileTest results in 
```
ai.rapids.cudf.CudfException: cuDF failure at: /rapids/spark-rapids-jni/thirdparty/cudf/java/src/main/native/src/CuFileJni.cpp:162: Failed to register cuFile handle: internal error
```

**Steps/Code to reproduce bug**
```
PARALLEL_LEVEL=6 ./build/build-in-docker clean install -DGPU_ARGCHS=native -Dtest=ai.rapids.cudf.CuFileTest#testCopyToFile
```

**Expected behavior**
should pass. 

**Environment details (please complete the following information)**
- local dev

**Additional context**
Probably need a cudf issue to have exceptions include the path on the filesystem.

**Comment by pxLi** [comment]
currently we just skip related tests in both cudf jni and plugin jni side. Yeah the issue would be better to be tackled in cudf side, like change the test triggered logic to not only rely on the libcufile.so. Since in most scenarios we just need it to do the compilation, but not all users have GDS devices available.

https://github.com/rapidsai/cudf/blob/branch-22.06/java/ci/build-in-docker.sh#L81
https://github.com/NVIDIA/spark-rapids-jni/blob/branch-22.06/ci/premerge-build.sh#L28

**Comment by gerashegalov** [comment]
BTW it turns out we exclude CuFileTest in cudf when USE_GDS != 0N https://github.com/rapidsai/cudf/blob/branch-22.06/java/pom.xml#L190 but this pom is not used in the spark-rapids-jni build
