### ISSUE TITLE
Look into dead code elimination to reduce static native lib size in the jar

### ISSUE THREAD

**Issue by gerashegalov** [NVIDIA/spark-rapids-jni#665]
nvcc: Eliminating unused kernels https://developer.nvidia.com/blog/reducing-application-build-times-using-cuda-c-compilation-aids/
- -rdc=true

gcc: https://gcc.gnu.org/onlinedocs/gnat_ugn/Compilation-options.html
 - add compiler flags `--ffunction-sections` and `--fdata-sections`
 - add to linker flags `--gc-sections`

**Comment by jlowe** [comment]
I don't think this is going to make much of a difference.  Everything the compiler sees is for a shared library, so it cannot know whether something is actually unused in practice since it does not see the final application leveraging the shared library.

I did originally reduce libcudf.so to just the methods that libcudfjni needed, and it does reduce the binary size a little.  However RAPIDS UDFs may reference APIs from libcudf.so that are not used by libcudfjni.so, so I left them in there.  We would have similar concerns of removing too much in light of RAPIDS UDFs usage that is outside the scope of the direct plugin usage of libcudf.so.

**Comment by jlowe** [comment]
Closing this since I don't think we can safely implement it given the need to support RAPIDS UDFs.  We may not refer to a libcudf kernel, but the user's UDF might.
